Remove nested dict facts
The combination of ansible 2.1.6.0 and config_template that we're using
doesn't seem to jive with these nested dicts.  When the dict is nested,
the resulting dictionary passed to config_template has keys/values that
are represented as type ansible.vars.unsafe_proxy.AnsibleUnsafeText,
instead of type unicode.  This results in yaml.safe_dump throwing the
following error:

```
RepresenterError: cannot represent an object: apply_security_hardening
```

Here we simply create separate dicts for each override rather than
nesting and looking up based on key.